---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../prometheus
  - ./default
  - ./scripts
  - ./quickstart.yaml
  - ./rbac

namespace: opendatahub
configMapGenerator:
  - envs:
      - params.env
    name: mesh-parameters
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    fieldPath: metadata.namespace
    kind: ConfigMap
    name: mesh-parameters
    version: v1
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      kind: ServiceAccount
      name: etcd-serviceaccount
      version: v1
  - fieldPaths:
    - subjects.*.namespace
    select:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: etcd-clusterrolebinding
      version: v1
- source:
    fieldPath: data.odh-modelmesh
    kind: ConfigMap
    name: mesh-parameters
    version: v1
  targets:
    - select:
        kind: ConfigMap
        name: model-serving-config-defaults
      fieldPaths:
        - data.[config-defaults.yaml]
      options:
        delimiter: '"'
        index: 5
- source:
    fieldPath: data.odh-mm-rest-proxy
    kind: ConfigMap
    name: mesh-parameters
    version: v1
  targets:
    - select:
        kind: ConfigMap
        name: model-serving-config-defaults
      fieldPaths:
        - data.[config-defaults.yaml]
      options:
        delimiter: '"'
        index: 15
- source:
    fieldPath: data.odh-modelmesh-runtime-adapter
    kind: ConfigMap
    name: mesh-parameters
    version: v1
  targets:
    - select:
        kind: ConfigMap
        name: model-serving-config-defaults
      fieldPaths:
        - data.[config-defaults.yaml]
      options:
        delimiter: '"'
        index: 25
- source:
    fieldPath: data.odh-modelmesh-controller
    kind: ConfigMap
    name: mesh-parameters
    version: v1
  targets:
    - select:
        kind: Deployment
        name: modelmesh-controller
      fieldPaths:
        - spec.template.spec.containers.0.image

labels:
  - pairs:
      app: model-mesh
      app.kubernetes.io/part-of: model-mesh
    includeSelectors: true
    includeTemplates: true

patches:
  - path: ./crd/clusterservingruntime_patch_delete.yaml

