# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


configMapGenerator:
- files:
  - config-defaults.yaml
  name: model-serving-config-defaults

generatorOptions:
  disableNameSuffixHash: true

namespace: system

transformers:
- metadataLabelTransformer.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../manager
- ../webhook
- ../certmanager

patches:
- path: manager_webhook_patch.yaml
- path: webhookcainjection_patch.yaml

replacements:
- source:
    fieldPath: metadata.namespace
    kind: Certificate
    name: modelmesh-webhook-server-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
    select:
      kind: ValidatingWebhookConfiguration
- source:
    kind: Certificate
    name: modelmesh-webhook-server-cert
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      kind: ValidatingWebhookConfiguration
- source:
    kind: Service
    name: modelmesh-webhook-server-service
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
    select:
      group: cert-manager.io
      kind: Certificate
      name: modelmesh-webhook-server-cert
      namespace: system
      version: v1
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: modelmesh-webhook-server-service
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: modelmesh-webhook-server-cert
      namespace: system
      version: v1
