resources:
- ../../crd/external
- ../../default

patches:
  - path: odh_model_controller_manager_patch.yaml

namespace: default
configMapGenerator:
- envs:
  - params.env
  name: odh-model-controller-parameters
generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      fieldPath: metadata.namespace
      kind: ConfigMap
      name: odh-model-controller-parameters
      version: v1
    targets:
    - select:
        kind: ClusterRoleBinding
      reject:
        - name: proxy-rolebinding
      options:
        delimiter: '-'
        index: 4
  - source:
      fieldPath: data.monitoring-namespace
      kind: ConfigMap
      name: odh-model-controller-parameters
      version: v1
    targets:
      - select:
          kind: Deployment
          name: odh-model-controller
        fieldPaths:
            - spec.template.spec.containers.*.env.[name=MONITORING_NS].value
