apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub
resources:
- ../../base
- ../../argo
patches:
- path: img_patch.yaml
images:
- name: controller
  newName: quay.io/opendatahub/data-science-pipelines-operator
  newTag: main
