resources:
- manager.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/component: kuberay-operator
      app.kubernetes.io/name: kuberay
    includeSelectors: true
    includeTemplates: true
