apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opendatahub
resources:
  - ../../base
patches:
  - path: img_patch.yaml
  - path: res_patch.yaml
  - path: user_patch.yaml
images:
  - name: controller
    newName: quay.io/opendatahub/data-science-pipelines-operator
    newTag: main
