apiVersion: apps/v1
kind: Deployment
metadata:
  name: odh-model-controller
spec:
  replicas: 3
  template:
    spec:
      containers:
        - args:
            - --leader-elect
          image: $(odh-model-controller) 
          name: manager
