apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../default
- user-cluster-roles.yaml

namespace: opendatahub

patches:
- path: remove-namespace.yaml
- path: inferenceservice-config-patch.yaml
- path: set-resources-manager-patch.yaml

replacements:
- source:
    kind: ConfigMap
    name: kserve-parameters
    fieldpath: data.kserve-controller
  targets:
  - select:
      kind: Deployment
      name: kserve-controller-manager
    fieldPaths:
    - spec.template.spec.containers.[name=manager].image
- source:
    fieldPath: data.kserve-storage-initializer
    kind: ConfigMap
    name: kserve-parameters
    version: v1
  targets:
  - select:
      kind: ConfigMap
      name: inferenceservice-config
    fieldPaths:
    - data.storageInitializer
    options:
      delimiter: '"'
      index: 3
- source:
    fieldPath: data.kserve-agent
    kind: ConfigMap
    name: kserve-parameters
    version: v1
  targets:
  - fieldPaths:
    - data.logger
    options:
      delimiter: '"'
      index: 3
    select:
      name: inferenceservice-config
      namespace: kserve
  - fieldPaths:
    - data.batcher
    options:
      delimiter: '"'
      index: 3
    select:
      namespace: kserve
      name: inferenceservice-config
  - fieldPaths:
    - data.agent
    options:
      delimiter: '"'
      index: 3
    select:
      name: inferenceservice-config
      namespace: kserve
- source:
    fieldPath: data.kserve-router
    kind: ConfigMap
    name: kserve-parameters
    version: v1
  targets:
  - fieldPaths:
    - data.router
    options:
      delimiter: '"'
      index: 3
    select:
      name: inferenceservice-config
      namespace: kserve

configMapGenerator:
- envs:
  - params.env
  name: kserve-parameters

generatorOptions:
  disableNameSuffixHash: true


configurations:
- params.yaml
