---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: opendatahub
labels:
  - pairs:
      app.kubernetes.io/part-of: odh-notebook-controller
      component.opendatahub.io/name: kf-notebook-controller
      opendatahub.io/component: "true"
    includeSelectors: true
    includeTemplates: true
images:
  - name: docker.io/kubeflownotebookswg/notebook-controller
    newName: quay.io/opendatahub/kubeflow-notebook-controller
    newTag: 1.7-d53909e
configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - USE_ISTIO=false
      - ADD_FSGROUP=false
patches:
  - path: remove_namespace_patch.yaml
  - path: manager_openshift_patch.yaml
  - path: manager_service_openshift_patch.yaml
