resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: stack-config
  envs:
    - params.env
configurations:
  - params.yaml

replacements:
- source:
    fieldPath: data.namespace
    kind: ConfigMap
    name: stack-config
    version: v1
  targets:
    - fieldPaths:
        - metadata.namespace
      select: {}
      options:
        create: true
- source:
    fieldPath: data.codeflare-operator-controller-image
    kind: ConfigMap
    name: stack-config
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.image
    select:
      group: apps
      kind: Deployment
      name: manager
      namespace: system
      version: v1
