apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub

configMapGenerator:
- name: ray-config
  envs:
    - params.env

replacements:
  - source:
      kind: ConfigMap
      name: ray-config
      version: v1
      fieldPath: data.namespace
    targets:
      - fieldPaths:
          - metadata.namespace
        select: {}
        options:
          create: true
      - select:
          kind: SecurityContextConstraints
          group: security.openshift.io
          version: v1
        fieldPaths:
          - users.*
        options:
          delimiter: ':'
          index: 2
  - source:
      kind: ConfigMap
      name: ray-config
      version: v1
      fieldPath: data.odh-kuberay-operator-controller-image
    targets:
      - select:
          group: apps
          kind: Deployment
          name: kuberay-operator
        fieldPaths:
          - spec.template.spec.containers.0.image

resources:
- ray_operator_scc.yaml
- ../default

labels:
  - pairs:
      app.kubernetes.io/name: kuberay
      app.kubernetes.io/component: kuberay-operator
    includeSelectors: true
    includeTemplates: true

patches:
- path: remove_default_namespace.yaml
