---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/blob/main/jupyter/pytorch"
    opendatahub.io/notebook-image-name: "PyTorch"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with PyTorch libraries and dependencies to start experimenting with advanced AI/ML notebooks."
    opendatahub.io/notebook-image-order: "40"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
  name: pytorch
spec:
  lookupPolicy:
    local: true
  tags:
    # N Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"},{"name":"PyTorch","version":"2.0"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"PyTorch","version":"2.0"},{"name":"Tensorboard","version":"2.13"},{"name":"Boto3","version":"1.28"},{"name":"Kafka-Python","version":"2.0"},{"name":"Kfp-tekton","version":"1.5"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.24"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.3"},{"name":"Scipy","version":"1.11"},{"name":"Elyra","version":"3.15"},{"name":"PyMongo","version":"4.5"},{"name":"Pyodbc","version":"4.0"}, {"name":"Codeflare-SDK","version":"0.14"}, {"name":"Sklearn-onnx","version":"1.15"}, {"name":"Psycopg","version":"3.1"}, {"name":"MySQL Connector/Python","version":"8.0"}]'
        openshift.io/imported-from: quay.io/modh/odh-pytorch-notebook
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-pytorch-gpu-notebook-image-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-pytorch-gpu-notebook-image-n_PLACEHOLDER
      name: "2023.2"
      referencePolicy:
        type: Source
    # N-1 Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.8"},{"name":"Python","version":"v3.9"},{"name":"PyTorch","version":"1.13"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"PyTorch","version":"1.13"},{"name":"Tensorboard","version":"2.11"},{"name":"Boto3","version":"1.26"},{"name":"Kafka-Python","version":"2.0"},{"name":"Kfp-tekton","version":"1.5"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.24"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.2"},{"name":"Scipy","version":"1.10"},{"name":"Elyra","version":"3.15"}]'
        openshift.io/imported-from: quay.io/modh/odh-pytorch-notebook
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: odh-pytorch-gpu-notebook-image-commit-n-1_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-pytorch-gpu-notebook-image-n-1_PLACEHOLDER
      name: "2023.1"
      referencePolicy:
        type: Source
    # N-2 Version of the image
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"CUDA","version":"11.4"},{"name":"Python","version":"v3.8"},{"name":"PyTorch","version":"1.8"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"PyTorch","version":"1.8"},{"name":"Tensorboard","version":"2.6"},{"name":"Boto3","version":"1.17"},{"name":"Kafka-Python","version":"2.0"},{"name":"Matplotlib","version":"3.4"},{"name":"Numpy","version":"1.19"},{"name":"Pandas","version":"1.2"},{"name":"Scikit-learn","version":"0.24"},{"name":"Scipy","version":"1.6"}]'
        openshift.io/imported-from: quay.io/modh/odh-pytorch-notebook
        opendatahub.io/image-tag-outdated: 'true'
        opendatahub.io/notebook-build-commit: odh-pytorch-gpu-notebook-image-commit-n-2_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-pytorch-gpu-notebook-image-n-2_PLACEHOLDER
      name: "1.2"
      referencePolicy:
        type: Source
