---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/red-hat-data-services/notebooks/tree/main/habana"
    opendatahub.io/notebook-image-name: "HabanaAI"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with a set of habana libraries that advanced AI/ML notebooks will use as a base image to provide a standard for libraries avialable in all notebooks"
    opendatahub.io/notebook-image-order: "70"
    opendatahub.io/recommended-accelerators: '["habana.ai/gaudi"]'
  name: habana-notebook
spec:
  lookupPolicy:
    local: true
  tags:
    # 1.10.0 Version of the image n
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"},{"name":"Habana","version":"1.10"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"Boto3","version":"1.26"},{"name":"Kafka-Python","version":"2.0"},{"name":"Kfp-tekton","version":"1.5"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.23"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.2"},{"name":"Scipy","version":"1.10"},{"name":"TensorFlow","version":"2.12.0"},{"name":"PyTorch","version":"2.0.1"},{"name":"Elyra","version":"3.15"}]'
        openshift.io/imported-from: quay.io/modh/odh-habana-notebooks
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: odh-habana-notebook-image-commit-n_PLACEHOLDER
      from:
        kind: DockerImage
        name: odh-habana-notebook-image-n_PLACEHOLDER
      name: "2023.2"
      referencePolicy:
        type: Source
