---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jupyter-minimal-notebook-imagestream.yaml
  - jupyter-datascience-notebook-imagestream.yaml
  - jupyter-habana-notebook-imagestream.yaml
  - jupyter-minimal-gpu-notebook-imagestream.yaml
  - jupyter-pytorch-notebook-imagestream.yaml
  - jupyter-tensorflow-notebook-imagestream.yaml
  - jupyter-trustyai-notebook-imagestream.yaml
  - code-server-notebook-imagestream.yaml
  - rstudio-buildconfig.yaml
  - cuda-rstudio-buildconfig.yaml

labels:
  - pairs:
      opendatahub.io/component: "true"
      component.opendatahub.io/name: notebooks
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - name: notebooks-parameters
    env: params.env
  - name: notebook
    env: commit.env
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    fieldPath: data.odh-minimal-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-n-2
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-n-2
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-n-2
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-n-2
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-n-2
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-trustyai-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: odh-trustyai-notebook
      version: v1
- source:
    fieldPath: data.odh-trustyai-notebook-image-n-1
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: odh-trustyai-notebook
      version: v1
- source:
    fieldPath: data.odh-habana-notebook-image-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: habana-notebook
      version: v1
- source:
    fieldPath: data.odh-codeserver-notebook-n
    kind: ConfigMap
    name: notebooks-parameters
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.from.name
    select:
      group: image.openshift.io
      kind: ImageStream
      name: code-server-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-notebook-image-commit-n-2
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-minimal-notebook
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-minimal-gpu-notebook-image-commit-n-2
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: minimal-gpu
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-pytorch-gpu-notebook-image-commit-n-2
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: pytorch
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-generic-data-science-notebook-image-commit-n-2
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: s2i-generic-data-science-notebook
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-tensorflow-gpu-notebook-image-commit-n-2
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.2.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: tensorflow
      version: v1
- source:
    fieldPath: data.odh-trustyai-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: odh-trustyai-notebook
      version: v1
- source:
    fieldPath: data.odh-trustyai-notebook-image-commit-n-1
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.1.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: odh-trustyai-notebook
      version: v1
- source:
    fieldPath: data.odh-habana-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: habana-notebook
      version: v1
- source:
    fieldPath: data.odh-codeserver-notebook-image-commit-n
    kind: ConfigMap
    name: notebook
    version: v1
  targets:
  - fieldPaths:
    - spec.tags.0.annotations.[opendatahub.io/notebook-build-commit]
    select:
      group: image.openshift.io
      kind: ImageStream
      name: code-server-notebook
      version: v1
