---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - jupyter-intel-ml-notebook-imagestream.yaml
  - jupyter-intel-pytorch-notebook-imagestream.yaml
  - jupyter-intel-tensorflow-notebook-imagestream.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: notebooks
