# RHOAI configuration for Kubeflow Training Operator (KFTO)

# Adds namespace to all resources.
namespace: opendatahub

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: kubeflow-

configMapGenerator:
- name: rhoai-config
  envs:
    - params.env

replacements:
- source:
    fieldPath: data.odh-training-operator-controller-image
    kind: ConfigMap
    name: rhoai-config
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.image
    select:
      group: apps
      kind: Deployment
      name: training-operator
      version: v1

# Labels to add to all resources and selectors.
labels:
  - pairs:
      app.kubernetes.io/name: training-operator
      app.kubernetes.io/component: controller
    includeSelectors: true
    includeTemplates: true

resources:
- ../base
- kubeflow-training-roles.yaml
- monitor.yaml

patches:
# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
- path: manager_config_patch.yaml
- path: manager_metrics_patch.yaml
- path: manager_delete_metrics_service_patch.yaml
