apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
spec:
  template:
    spec:
      containers:
      - name:  training-operator
        image: image_PLACEHOLDER
        args:
        - "--zap-log-level=2"
