apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prometheus
  - ../overlays/odh

namespace: opendatahub
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    fieldPath: metadata.namespace
    kind: ConfigMap
    name: odh-model-controller-parameters
    version: v1
  targets:
    - select:
        kind: ClusterRoleBinding
      options:
        delimiter: '-'
        index: 4
- source:
    fieldPath: data.odh-model-controller
    kind: ConfigMap
    name: odh-model-controller-parameters
    version: v1
  targets:
    - select:
        kind: Deployment
        name: odh-model-controller
      fieldPaths:
        - spec.template.spec.containers.0.image
