---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      opendatahub.io/component: "true"
      component.opendatahub.io/name: notebooks
    includeSelectors: true
    includeTemplates: true
