---
namePrefix: trustyai-service-operator-

resources:
  - ../crd
  - ../rbac
  - ../manager

labels:
  - pairs:
      app.kubernetes.io/part-of: trustyai
    includeSelectors: true
    includeTemplates: true

configMapGenerator:
  - env: params.env
    name: config

generatorOptions:
  disableNameSuffixHash: true

replacements:
#  - source:
#      kind: ConfigMap
#      name: config
#      version: v1
#      fieldPath: data.trustyaiServiceImage
  - source:
      kind: ConfigMap
      name: config
      version: v1
      fieldPath: data.trustyaiOperatorImage
    targets:
      - select:
          group: apps
          kind: Deployment
          name: controller-manager
        fieldPaths:
          - spec.template.spec.containers.0.image
#  - source:
#      kind: ConfigMap
#      name: config
#      version: v1
#      fieldPath: data.oauthProxyImage
