# Adds namespace to all resources.
namespace: opendatahub

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: codeflare-operator-

# Labels to add to all resources and selectors.
labels:
  - pairs:
      app.kubernetes.io/name: codeflare-operator
      app.kubernetes.io/part-of: codeflare
    includeSelectors: true
    includeTemplates: true

resources:
- ../rbac
- ../manager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
# - ../prometheus
- metrics_service.yaml
